from pathlib import Path
import xml.etree.cElementTree as ET

from otlmow_converter.DotnotationHelper import DotnotationHelper
from otlmow_model.OtlmowModel.BaseClasses.OTLObject import dynamic_create_type_from_uri, get_attribute_by_name, \
    get_attribute_by_uri, dynamic_create_instance_from_uri
from otlmow_modelbuilder.OSLOCollector import OSLOCollector


class XSDCreator:
    def _create_starting_xml(self):
        pass





        #           <xs:element name="afmeting_hoogte" minOccurs="0" default="">
        #             <xs:annotation>
        #               <xs:documentation>De hoogte in millimeter.</xs:documentation>
        #             </xs:annotation>
        #             <xs:simpleType>
        #               <xs:restriction base="xs:decimal">
        #                 <xs:totalDigits value="19" />
        #                 <xs:fractionDigits value="10" />
        #               </xs:restriction>
        #             </xs:simpleType>
        #           </xs:element>


    @classmethod
    def create_xsd_from_subset(cls, subset_path, xsd_path):
        collector = OSLOCollector(subset_path)
        collector.collect_all(include_abstract=True)

        import xml.etree.cElementTree as ET

        schema = ET.Element("{http://www.w3.org/2001/XMLSchema}schema", targetNamespace="http://fdo.osgeo.org/schemas/feature/Schema1",  elementFormDefault="qualified", attributeFormDefault="unqualified" )
        annotation = ET.SubElement(schema, "{http://www.w3.org/2001/XMLSchema}annotation")
        documentation = ET.SubElement(annotation, "{http://www.w3.org/2001/XMLSchema}documentation")
        documentation.text = "Default schema"

        tree = ET.ElementTree(schema)
        tree.write("filename.xml")

        ET.register_namespace("xs", 'http://www.w3.org/2001/XMLSchema')
        ET.register_namespace("fdo", 'http://fdo.osgeo.org/schemas')
        ET.register_namespace("gml", 'http://www.opengis.net/gml')
        ET.register_namespace("Schema1", 'http://fdo.osgeo.org/schemas/feature/Schema1')

        classes = collector.classes
        for class_ in classes:
            if class_.abstract:
                continue
            class_element = ET.SubElement(schema, "{http://www.w3.org/2001/XMLSchema}element", name=f"OTL_{class_.name}", type=f"Schema1:OTL_{class_.name}Type", abstract="false", substitutionGroup="gml:_Feature")
            key = ET.SubElement(class_element, "{http://www.w3.org/2001/XMLSchema}key", name=f"OTL_{class_.name}Key")
            selector = ET.SubElement(key, "{http://www.w3.org/2001/XMLSchema}selector", xpath=f".//OTL_{class_.name}")
            field = ET.SubElement(key, "{http://www.w3.org/2001/XMLSchema}field", xpath="FeatId")

            class_instance = dynamic_create_instance_from_uri(class_.objectUri)

            complex_type = ET.SubElement(schema, "{http://www.w3.org/2001/XMLSchema}complexType", name=f"OTL_{class_.name}Type", abstract="false", fdo_geometryName="Geometry")
            annotation = ET.SubElement(complex_type, "{http://www.w3.org/2001/XMLSchema}annotation")
            documentation = ET.SubElement(annotation, "{http://www.w3.org/2001/XMLSchema}documentation")
            documentation.text = class_instance.__doc__
            complex_content = ET.SubElement(complex_type, "{http://www.w3.org/2001/XMLSchema}complexContent")
            extension = ET.SubElement(complex_content, "{http://www.w3.org/2001/XMLSchema}extension", base="gml:AbstractFeatureType")
            attribute_sequence = ET.SubElement(extension, "{http://www.w3.org/2001/XMLSchema}sequence")


            feat_id = ET.SubElement(attribute_sequence, "{http://www.w3.org/2001/XMLSchema}element", name="FeatId", readOnly="true", autogenerated="true")
            annotation = ET.SubElement(feat_id, "{http://www.w3.org/2001/XMLSchema}annotation")
            documentation = ET.SubElement(annotation, "{http://www.w3.org/2001/XMLSchema}documentation")
            documentation.text = "Default identity property"
            simple_type = ET.SubElement(feat_id, "{http://www.w3.org/2001/XMLSchema}simpleType")
            restriction = ET.SubElement(simple_type, "{http://www.w3.org/2001/XMLSchema}restriction", base="xs:int")

            # TODO use _geometry_types
            geometry = ET.SubElement(attribute_sequence, "{http://www.w3.org/2001/XMLSchema}element", name="Geometry", type="gml:AbstractGeometryType", fdo_hasMeasure="false", fdo_hasElevation="true", fdo_srsName="Default", fdo_geometricTypes="point multipoint polygon multipolygon ", fdo_geometryTypes="point multipoint polygon multipolygon ")
            annotation = ET.SubElement(geometry, "{http://www.w3.org/2001/XMLSchema}annotation")
            documentation = ET.SubElement(annotation, "{http://www.w3.org/2001/XMLSchema}documentation")
            documentation.text = "Default geometry property"

            #           <xs:element name="afmeting_breedte" minOccurs="0" default="">
            #             <xs:annotation>
            #               <xs:documentation>De breedte in millimeter.</xs:documentation>
            #             </xs:annotation>
            #             <xs:simpleType>
            #               <xs:restriction base="xs:decimal">
            #                 <xs:totalDigits value="19" />
            #                 <xs:fractionDigits value="10" />
            #               </xs:restriction>
            #             </xs:simpleType>
            #           </xs:element>

            attribute_names_of_subset = [attribuut.name for attribuut in collector.find_attributes_by_class(class_)]
            class_instance.fill_with_dummy_data()

            for dotnotation, _ in DotnotationHelper.list_attributes_and_values_by_dotnotation(class_instance, waarde_shortcut=True):
                first_in_dotnotation = dotnotation
                if '.' in first_in_dotnotation:
                    first_in_dotnotation = first_in_dotnotation.split('.')[0]
                if '[]' in first_in_dotnotation:
                    first_in_dotnotation = first_in_dotnotation[:-2]
                if first_in_dotnotation not in attribute_names_of_subset:
                    continue

                attr_instance = DotnotationHelper.get_attribute_by_dotnotation(class_instance, dotnotation)
                definition = attr_instance.definition
                if hasattr(attr_instance.owner, '_parent'):
                    o = attr_instance.owner._parent
                    if o.field.waarde_shortcut_applicable:
                        dotnotation = DotnotationHelper.get_dotnotation(o)
                        definition = o.definition

                print(attr_instance.naam, attr_instance.field.naam)


                element = ET.SubElement(attribute_sequence, "{http://www.w3.org/2001/XMLSchema}element", name=dotnotation.replace('.', '_'), minOccurs="0", default="")
                annotation = ET.SubElement(element, "{http://www.w3.org/2001/XMLSchema}annotation")
                documentation = ET.SubElement(annotation, "{http://www.w3.org/2001/XMLSchema}documentation")
                documentation.text = definition
                simple_type = ET.SubElement(element, "{http://www.w3.org/2001/XMLSchema}simpleType")
                restriction = ET.SubElement(simple_type, "{http://www.w3.org/2001/XMLSchema}restriction", base="xs:decimal")
                total_digits = ET.SubElement(restriction, "{http://www.w3.org/2001/XMLSchema}totalDigits", value="19")
                fraction_digits = ET.SubElement(restriction, "{http://www.w3.org/2001/XMLSchema}fractionDigits", value="10")


        tree.write(xsd_path)

def test_create_xsd_from_subset():
    kast_path = Path(__file__).parent / 'subset_wegkantkast.db'

    XSDCreator.create_xsd_from_subset(kast_path, Path(__file__).parent / 'created_wegkantkast.xsd')
