name: Coverage
run-name: Coverage for ${{ github.sha }}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  coverage:
    timeout-minutes: 10
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./UnitTests
    steps:
      - uses: actions/checkout@v4
      - name: Install uv with Python version 3.13
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
      - name: Installing dependencies with uv for running the tests
        run: uv pip install -r ../pyproject.toml --extra test
      - name: Run unittests with pytest and coverage
        run: python -m pytest --cov -v --cov-report=html
      - name: Coverage Badge.
        uses: tj-actions/coverage-badge-py@v2
        with:
          working-directory: ./UnitTests
      - name: Remove .gitignore from htmlcov
        run: rm -f ./htmlcov/.gitignore
      - name: Commit files
        run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated coverage.svg"
          git push
