name: Unittests
run-name: Unittests for ${{ github.sha }}
on: [push]

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.13']
    steps:
      - uses: actions/checkout@v3
      - name: Install uv with Python version ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies with uv for running the tests
        run: uv pip install -r pyproject.toml --extra test
      - name: Install additional OS dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libegl1
      - name: Run unittests with pytest
        run: python -m pytest -v
        working-directory: .